tasks:
  - init: npm install
    command: npm run watch
  - init: |
      php -r "file_exists('.env') || copy('.env.example', '.env');"
      composer install -q --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      php artisan key:generate
      chmod -R 777 storage bootstrap/cache
      mkdir -p database
      touch database/database.sqlite
    command: php artisan serve
  - init: |
      alias artisan='php artisan'
      alias phpunit='./vendor/bin/phpunit'
    command: echo "artisan|phpunit" command is available here
    
ports:
  - port: 8000
