name: Request New Guest Pass

on:

  repository_dispatch:
    types: [parking-pass-register]

jobs:
  guest-pass:

    runs-on: ubuntu-latest
    env:
      SP_PERSON_VEHICLE_CONFIG: ${{ secrets.personVehicleConfig }}
      SP_PROPERTY_ADDRESS: ${{ secrets.propertyAddress }}
      SP_CONTACT_FIRST_NAME: Jose
      SP_CONTACT_LAST_NAME: Pacheco
      SP_CONTACT_EMAIL: jose@icheko.com
      SP_CONTACT_PHONE: ${{ secrets.contactPhone }}
    steps:
    - uses: actions/checkout@v2
    - name: Client Payload
      run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Upgrade Chrome Driver
      run: php artisan dusk:chrome-driver 80
    - name: Start Chrome Driver
      run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &
    - name: Run Laravel Server
      run: php artisan serve > /dev/null 2>&1 &
    - name: Request New Guest Pass
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        REQUEST_GUEST_PASS_PERSON: ${{ github.event.client_payload.person }}
      run: vendor/bin/phpunit --filter requestGuestPass --group ignore
